name: WsWriteSign
main: WsWriteSign\WMain
load: STARTUP
version: 1.0.0
author: Wshape1
api: 
- 1.0.0
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
commands:
 wws:
  description: §e 指令改写木牌